// Renders the generic share card to public/images/og-card.png.
//
// The card that social crawlers actually fetch is generated by
// app/opengraph-image.tsx at a build-hashed URL. This committed copy exists only
// so lib/structured-data.ts has a stable, constructible URL for the BlogPosting
// `image` of posts that have no hero image.
//
// Run with `npm run og:card` after changing the card design.

import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { renderPageCard } from '../lib/og-image';

async function main(): Promise<void> {
    const response = await renderPageCard();
    const bytes = Buffer.from(await response.arrayBuffer());
    const target = join(process.cwd(), 'public', 'images', 'og-card.png');

    await writeFile(target, bytes);
    console.log(`public/images/og-card.png — ${bytes.byteLength} bytes`);
}

main().catch((error: unknown) => {
    console.error(error);
    process.exit(1);
});
